ph-ee-g2psandbox:
  ph-ee-engine:
    post_installation_job:
      enabled: false
    elasticsearch:
      enabled: false
    kibana:
      enabled: false
    messagegateway:
      enabled: false
    notifications:
      enabled: false
    operations_web:
      enabled: false
    importer_es:
      enabled: false
    ph_ee_connector_ams_mifos:
      enabled: true
      ams_local_interop_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_account_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_customer_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_auth_host: "https://fynams.sandbox.fynarfin.io/"
