ph-ee-g2psandbox:
  ph-ee-engine:
    importer_es:
      enabled: false
    elasticsearch:
      enabled: false
      volumeClaimTemplate:
        storageClassName: standard
    ph-ee-connector:
      enabled: false
    ph_ee_connector_gsma:
      enabled: false
    ph_ee_connector_mojaloop:
      enabled: false
    vouchers:
      enabled: false
    importer_rdbms:
      enabled: false
    importer_es:
      enabled: false
    mockpayment:
      enabled: false
    kibana:
      enabled: false
    kafka:
      provisioning:
        enabled: false
      global:
        storageClass: standard
    messagegateway:
      enabled: false
    notifications:
      enabled: false
    operations_web:
      enabled: false
