ph-ee-g2psandbox:
  ph-ee-engine:
    post_installation_job:
      enabled: true
    importer_es:
      enabled: false
    ph_ee_connector_ams_mifos:
      enabled: false
    crm:
      enabled: false
    billPay:
      enabled: false
    kibana:
      enabled: false
    messagegateway:
      enabled: false
    notifications:
        enabled: false
    operations_web:
      enabled: false
    elasticsearch:
      enabled: false
      volumeClaimTemplate:
        storageClassName: standard

